### ISSUE TITLE
Not following iframes relative links

### ISSUE THREAD

**Issue by joshwegener** [webrecorder/browsertrix-crawler#45]
I'm having issues pulling links from an iframe (it does not seem to follow them)

`<iframe src="./somesite/Pages/This%20Is%20the%20'link'.html" scrollbars="1" height="900" width="100%"></iframe>`

I'm trying to scrape a site and just get a list of all the URLs on the site to send over to ArchiveBox for backup.

Also is there a simple way to just get the URLs and not the text?

This is my config:
```
    browsertrixcrawler:
        image: webrecorder/browsertrix-crawler
        command: crawl --url https://example.com/ --workers 2 --generateWACZ --text --collection otrlib
        volumes:
            - /data/archivebox/crawls:/crawls
        network_mode: service:vpn
        depends_on:
          - vpn
```

Thanks!
