### ISSUE TITLE
`--allowHashUrls` option silently does nothing

### ISSUE THREAD

**Issue by Mr0grog** [webrecorder/browsertrix-crawler#790]
The crawler has a documented [`--allowHashUrls` option](https://github.com/webrecorder/browsertrix-crawler/blob/34a1e3d6c03aceae899c36012d28a048008be0c6/src/util/argParser.ts#L164-L167), but it doesn’t appear to do anything. Searching the codebase, I can’t find any references to it except for the argument parser, so it doesn’t seem to actually be used.

I had expected this to allow a seed I’d listed with a hash URL to get captured. For example, using the following config:

```yaml
scopeType: page
allowHashUrls: true

seeds:
  - 'https://www.eia.gov/naturalgas/ngqs/#?report=RP9&year1=2017&year2=2017&company=Name'
```

Is this something that’s just not hooked up, or maybe a vestigial feature that was supposed to be removed?

The workarounds I’m currently trying are:

```yaml
scopeType: page
include: ['.*']
```

or:

```yaml
scopeType: custom
depth: 0
include: ['.*']
```

or:

```yaml
scopeType: custom
depth: 0

seeds:
  - url: 'https://www.eia.gov/naturalgas/ngqs/#?report=RP9&year1=2017&year2=2017&company=Name'
    allowHash: true
```

(Side note: I’d hoped I could use `allowHash` on the seed with `scopeType: page` at the top level, but it looks like [that scope type always prevents `allowHash` from being configured](https://github.com/webrecorder/browsertrix-crawler/blob/34a1e3d6c03aceae899c36012d28a048008be0c6/src/util/seeds.ts#L163-L168), which seems less than ideal.)
