### ISSUE TITLE
More blocking rules examples in README.md

### ISSUE THREAD

**Issue by billsargent** [webrecorder/browsertrix-crawler#80]
Could you provide a couple more examples of blockingRules on the README? 

I'm moving away from httrack and I'm having trouble figuring out how to block urls like https://www.dummyurl.com/gallery/* 

I've tried regex and just plain simple urls in a yaml...

```
blockRules:
- url: dummyurl.com/gallery/
  type: block
- url: /^https://www\.dummyurl\.com/gallery/[a-zA-Z]+$/i
  type: block
```
 
 But all I get after a few minutes of running the container is 
 
```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);.361
              ^

Error: Request is already handled! 
    at Object.assert (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26:15)
    at HTTPRequest.abort (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:308:21)ihavenreborn.com/auth/login
    at BlockRules.handleRequest (/app/util/blockrules.js:97:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/util/blockrules.js:70:9
```
 
I'm positive this is something very basic that I'm not understanding. Any help would be appreciated.

**Comment by ikreymer** [comment]
Thanks for reporting, that is an odd error message, will look into that.

Since standard YAML doesn't support regexes, the rules should just be strings. Try:

```
blockRules:
- url: dummyurl.com/gallery/
  type: block
- url: "https://www\.dummyurl\.com/gallery/[a-zA-Z]+$"
  type: block
```

If you run with `--logging stats,debug`, you should also get a printout of how the blockRules have been parsed in JS.
