### ISSUE TITLE
Feature - Nested seed rules

### ISSUE THREAD

**Issue by DrMint** [webrecorder/browsertrix-crawler#83]
Hi again! So I've been trying to create this specific crawling rule:
_Crawl all pages that have this prefix: "https://example.com", and for all outbound links, crawl no further than the link's destination page_. I believe this isn't possible right now but here's what I think I think it could look like:

```
seeds:
  - url: https://example.com
    scopeType: prefix
    include:
      - url: /.*/
        scopeType: page
```
I think that would work if only the rules corresponding to the first valid "include" regex are used. So here, the implied [/^https:\/\/example\.com/ rule would take precedence over /.*/ (if not, it would change the scopeType of example.com pages too)

It could lead to more complex behaviors such as:
```
seeds:
  - url: https://example.com
    scopeType: prefix
    include:
      - url: github.com
        depth: 2
      - url: /.*/
        scopeType: page
```
I would say, it's a bit like generating a seedfile on the fly, and applying seed rules on its urls. Or it could be seen as seed rules applied only on pages with a given referring domain (here example.com). There is probably a lot of little details to think about to avoid weird parsing issues and unwanted behaviors.

For now, I'll just crawl my target domain once. Then redo a crawl on the same collection using a seedfile containing all the outbound links and a scopeType set to page.
