### ISSUE TITLE
Support host-specific proxy settings.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#836]
It is often useful to be able to set up host-specific proxy, to route certain traffic through a proxy, or use different proxies for different domains, matched by regex.

This can be configured through a separate proxy yaml file (or could be part of the same settings as the existing config with new keys added).

This can be implemented with proxy PAC scripts which are supported in Brave (and support socks5 auth!). The crawler can generate a proxy PAC script from a config file that and pass that to the browser.

The config file could look as follows, for example:

```yaml
matchHosts:
  # load all URLs from example.com through 'example-1-proxy'
  example.com/.*: example-1-proxy 

  # load all URLS from https://my-social.example.com/.*/posts/ through
  # a different proxy
  https://my-social.example.com/.*/posts/: social-proxy

  # optional default proxy
  "": default-proxy

proxies:
  # SOCKS5 proxy just needs a URL
  example-1-proxy: socks5://username:password@my-socks-5-proxy.example.com

  # SSH proxy also should have at least a 'privateKeyFile'
  social-proxy:
    url: ssh://user@my-social-proxy.example.com
    privateKeyFile: /proxies/social-proxy-private-key
    # optional
    publicHostsFile: /proxies/social-proxy-public-hosts

  default-proxy:
    url: ssh://user@my-social-proxy.example.com
    privateKeyFile: /proxies/default-proxy-private-key
```
