### ISSUE TITLE
v.split is not a function, using config file

### ISSUE THREAD

**Issue by lakonis** [webrecorder/browsertrix-crawler#839]
I successfully crawl and collect data with this command : 

```bash
docker run -p 9037:9037 -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl 
  --url https://mysite.com 
  --generateWACZ 
  --text 
  --sitemap 
  --screenshot thumbnail 
  --collection mysite 
  --screencastPort 9037
```

To simplify the command, I am trying to use config file but i run into this error : `v.split is not a function`.

My config file `mysite.yaml`

```yaml
seeds:
  - url: https://mysite.com
    scopeType: "page"

generateWACZ: true
text: true
sitemap: true
screenshot: thumbnail
collection: mysite
screencastPort: 9037
```

and the command I used : 

`docker run  -p 9037:9037 -v $PWD/mysite.yaml:/app/mysite.yaml -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --config /app/mysite.yaml` 

Note1: using `--config stdin` produces the same error. 

Note2: I can simplify the config file and pass all options via the command (except seed). It runs well but then what is the point of using config. 

What am I doing wrong? Thanks for your help !
