### ISSUE TITLE
Facebook autoscroll not working

### ISSUE THREAD

**Issue by lakonis** [webrecorder/browsertrix-crawler#840]
Using browsertrix-crawler to crawl a facebook page, with the following config file and command : 

```yaml
  seeds:
  - url: https://www.facebook.com/UnMondeIncertain/
    scopeType: "page"
  generateWACZ: true
  text: to-pages
  screenshot: thumbnail,view
  screencastPort: 9037
  behaviors:
    - autoscroll
    - siteSpecific
    - autoplay
    - autofetch
```
```bash
cat ./myconfig.yaml | docker run -i -p 9037:9037 -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl \
      --config stdin  \
      --profile /crawls/profiles/profile.tar.gz \
      --behaviorTimeout 36000 \
      --collection mycollection
```

However, the scroll stops after 7 posts, whatever behaviors or timeout I set, or even when I set no behaviors nor timeout. 
Am I missing something to activate autoscroll on Facebook  ?
